[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/pallet-contracts",
    "pallets/iot-identity",
    "pallets/pallet-abac",
    "pallets/pallet-did",
    "runtime",
]
[profile.release]
panic = "unwind"
